const getTitles = (): string[] => {
  return [
    'A JavaScript program to display the current day and time.',
    'A JavaScript program to print the contents of the current window.',
    'A JavaScript program to get the current date.',
    'A JavaScript program to find the area of a triangle where lengths of the three of its sides are given.',
    "A JavaScript program to rotate the string 'w3resource' in right direction by periodically removing  one letter from the end of the string and attaching it to the front.",
    'A JavaScript program to determine whether a given year is a leap year in the Gregorian calendar.',
    'A JavaScript program to find 1st January is being a Sunday between 2014 and 2050.',
    "A JavaScript program where the program takes a random integer between 1 to 10, the user input a guess  number. If the user input matches with guess number, the program will display a message 'Good Work'  otherwise display a message 'Not matched'.",
    'A JavaScript program to calculate days left until next Christmas.',
    'A JavaScript program to calculate multiplication and division of two numbers.',
    'A JavaScript program to convert temperatures to and from Celsius, Fahrenheit.',
    'A JavaScript program to get the website URL (loading page).',
    'A JavaScript exercise to create a variable using a user-defined name.',
    'A JavaScript exercise to get the extension of a filename.',
    'A JavaScript program to get the difference between a given number and 13, if the number is greater than 13 return double the absolute difference.',
    'A JavaScript program to compute the sum of the two given integers. If the two values are same, then returns triple their sum.',
    'A JavaScript program to compute the absolute difference between a specified number and 19. Returns triple their absolute difference if the specified number is greater than 19.',
    'A JavaScript program to check two given numbers and return true if one of the number is 50 or if their sum is 50.',
    'A JavaScript program to check whether a given integer is within 20 of 100 or 400.',
    'A JavaScript program to check from two given integers, whether one is positive and another one is negative.',
    "A JavaScript program to create a new string adding 'Py' in front of a given string. If the given string begins with 'Py' then return the original string.",
    'A JavaScript program to remove a character at the specified position of a given string and return the new string.',
    'A JavaScript program to create a new string from a given string changing the position of first and last characters. The string length must be greater than or equal to 1.',
    'A JavaScript program to create a new string from a given string with the first character of the given string added at the front and back.',
    'A JavaScript program to check whether a given positive number is a multiple of 3 or a multiple of 7.',
    'A JavaScript program to create a new string from a given string taking the last 3 characters and added at both the front and back. The string length must be 3 or more.',
    "A JavaScript program to check whether a string starts with 'Java' and false otherwise.",
    'A JavaScript program to check whether two given integer values are in the range 50..99 (inclusive). Return true if either of them are in the said range.',
    'A JavaScript program to check whether three given integer values are in the range 50..99 (inclusive). Return true if one or more of them are in the said range.',
    "A JavaScript program to check whether a string 'Script' presents at 5th (index 4) position in a given string, if 'Script' presents in the string return the string without 'Script' otherwise return the original one.",
    'A JavaScript program to find the largest of three given integers.',
    'A JavaScript program to find a value which is nearest to 100 from two different given integer values.',
    'A JavaScript program to check whether two numbers are in range 40..60 or in the range 70..100 inclusive.',
  ];
};

export default getTitles;
